# GNU Make solution makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  angle_test_config = debug
endif
ifeq ($(config),release)
  angle_test_config = release
endif

PROJECTS := angle-test

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

angle-test:
ifneq (,$(angle_test_config))
	@echo "==== Building angle-test ($(angle_test_config)) ===="
	@${MAKE} --no-print-directory -C . -f angle-test.make config=$(angle_test_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f angle-test.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   angle-test"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
